### ISSUE TITLE
Problème de screenshot.jpg avec Cakephp

### ISSUE THREAD

**Issue by julienapprioual** [Alex-D/HomeWAMP#3]
Salut, super boulot! J'ai tout de suite adoré, l'interface est propre et va à l’essentiel.

Cependant un petit problème avec cakephp ==> il essaye de chercher le contrôleur screenshot.php.

J'ai réglé le problème en modifiant le .htaccess de la racine de cakephp en y ajoutant une ligne: 

<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule    ^$ app/webroot/    [L]
   RewriteCond %{REQUEST_FILENAME} !screenshot.jpg
   RewriteRule    (.*) app/webroot/$1 [L]
</IfModule>

En espérant que ça aidera d'autres personnes...

**Comment by Alex-D** [comment]
Merci pour ta contribution, malheuresement je ne peux l'intégrer d'une quelconque manière au code. Je vais rajouter une partie dans le README :)

**Comment by bastien625** [comment]
Chouette .. Projet 
DSL chui pas CODEUR et je découvre Github en Amateur
  Mais une juste une idée / PB ( sur CAKE.PHP que je Connais pas ) . . 
   Nom de Dossier :  _h5ai
   Nom de Vignette Standard :  _h5ai_screenshoot.jpg
Bonne Journée
