### ISSUE TITLE
Undefined offset: 1 in D:\wamp64\www\index.php on line 203

### ISSUE THREAD

**Issue by Crabtronic** [Alex-D/HomeWAMP#6]
Bonjour,

J'essaie de mettre en place la page homewamp et j'obtiens ces erreurs :

Notice: Undefined offset: 1 in D:\wamp64\www\index.php on line 203
Notice: Undefined offset: 1 in D:\wamp64\www\index.php on line 205
Notice: Undefined offset: 1 in D:\wamp64\www\index.php on line 207

Je n'ai également pas l'onglet "Administration" en haut à droite.

Merci pour cette page très utile.

@ bientôt

**Comment by Alex-D** [comment]
Salut,

comme tu peux le voir à la date du dernier commit, on était pas encore en WampServer 3. Je n'ai pas mis à jour depuis, il est probable que ça vienne de là.

Je n'utilise plus WAMP depuis un bon moment (Docker, tout ça tout ça) donc si tu veux corriger, je ne suis pas contre une Pull Request, mais sinon ça restera pour du WAMP 2.
